# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-09 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='img',
            field=models.ImageField(default='images/img.JPG', upload_to=b''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='has_apt',
            field=models.BooleanField(default=False),
        ),
    ]
