# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-09 23:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('useraccount', '0002_auto_20160609_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('rooms', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('roommates', models.IntegerField()),
                ('vacancy', models.IntegerField()),
                ('laundry', models.BooleanField()),
                ('internet', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
