# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-10 21:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0003_apartments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment_images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=255)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useraccount.Apartments')),
            ],
        ),
    ]
