# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-10 21:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0002_auto_20160610_2144'),
        ('useraccount', '0004_apartment_images'),
    ]

    operations = [
    ]
